[build-system]
requires = ["setuptools>=40.6.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyramid-otelapm"
version = "1.0.1"
description = "OpenTelemetry APM integration for the Pyramid framework"
readme = "README.rst"
license = { text = "BSD" }
authors = [
    { name = "Sebastian Wehrmann (riscLOG Solution GmbH)", email = "sebastian@risclog.com" },
]
keywords = ["opentelemetry", "otel", "apm", "pyramid"]
classifiers = [
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3 :: Only",
]
requires-python = ">=3.11"
dependencies = [
    "opentelemetry-api",
    "opentelemetry-exporter-otlp-proto-http",
    "opentelemetry-instrumentation-pyramid",
    "opentelemetry-sdk",
    "pyramid",
]

[project.urls]
Homepage = "https://github.com/risclog-solution/pyramid-otelapm"

[project.optional-dependencies]
requests = ["opentelemetry-instrumentation-requests"]
botocore = ["opentelemetry-instrumentation-botocore"]
sqlalchemy = ["opentelemetry-instrumentation-sqlalchemy"]
logging = ["opentelemetry-instrumentation-logging"]
test = [
    "pytest",
    "pytest-cache",
    "pytest-cov",
    "pytest-rerunfailures",
    "pytest-sugar",
    "webtest",
    "pytest_localserver",
    "opentelemetry-instrumentation-requests",
    "opentelemetry-instrumentation-botocore",
    "opentelemetry-instrumentation-sqlalchemy",
    "opentelemetry-instrumentation-logging",
    "sqlalchemy",
    "boto3",
]

[tool.setuptools]
zip-safe = false
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.coverage.run]
relative_files = true
parallel = true
branch = true
source = ["pyramid_otelapm"]

[tool.coverage.paths]
source = ["src", ".pytest/*/site-packages"]

[tool.coverage.html]
directory = "coverage-report"

[tool.coverage.report]
precision = 2
show_missing = true
skip_covered = true
exclude_lines = [
    # a more strict default pragma
    "\\# pragma: no cover\\b",

    # allow defensive code
    "^\\s*raise AssertionError\\b",
    "^\\s*raise NotImplementedError\\b",
    "^\\s*return NotImplemented\\b",
    "^\\s*raise$",

    # typing-related code
    "^if (False|TYPE_CHECKING):",
    ": \\.\\.\\.(\\s*#.*)?$",
    "^ +\\.\\.\\.$",
    "-> ['\"]?NoReturn['\"]?:",
]

[tool.black]
line-length = 79
target-version = ['py312']
exclude = '''
/(
    \.eggs
  | eggs
  | venv
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
skip-string-normalization = true
